### ISSUE TITLE
cdk bootstrap version

### ISSUE THREAD

**Issue by gabibeedigital** [purecloudlabs/audiohook-reference-implementation#9]
Hi guys,

I'm facing another error executing the command `npm run cdk-synth`:

```
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.
```

These are the installed modules:

```
> npm list 
audiohook-fargate@1.0.2 ....
├── @types/jest@28.1.8
├── @types/node@16.18.68
├── @typescript-eslint/eslint-plugin@5.62.0
├── @typescript-eslint/parser@5.62.0
├── aws-cdk-lib@2.115.0
├── aws-cdk@2.115.0
├── constructs@10.3.0
├── dotenv@16.3.1
├── eslint@8.56.0
├── jest@28.1.3
├── source-map-support@0.5.21
├── ts-jest@28.0.8
├── ts-node@10.9.2
└── typescript@4.8.4
```
